//.\constants\post.ts
const postsData = [
    {
        id: 1,
        title: "Exploring the Stars",
        body: "The universe is vast and full of mysteries. Scientists are constantly discovering new celestial bodies and phenomena. Understanding the cosmos helps us understand our place in it.",
        date: "2024-10-01",
        image: "https://vk.com/sticker/1-91857-512",
        comments: [],
    },
    {
        id: 2,
        title: "The Art of Cooking",
        body: "Cooking is both an art and a science. It requires precision, creativity, and a love for flavors. From simple dishes to gourmet meals, cooking brings joy to many.",
        date: "2024-10-02",
        image: "https://vk.com/sticker/1-917-512",
        comments: [],
    },
    {
        id: 3,
        title: "Journey to the Mountains",
        body: "Mountains offer breathtaking views and a sense of peace. Hiking through mountain trails is a popular activity for nature enthusiasts. The fresh air and scenic landscapes are rejuvenating.",
        date: "2024-10-03",
        image: "https://vk.com/sticker/1-917-512",
        comments: [],
    },
    {
        id: 4,
        title: "Advancements in Technology",
        body: "Technology is evolving at a rapid pace. Innovations in AI, robotics, and computing are transforming industries. Staying updated with tech trends is crucial in today's world.",
        date: "2024-10-04",
        image: "https://vk.com/sticker/1-917-512",
        comments: [],
    },
    {
        id: 5,
        title: "The World of Literature",
        body: "Books have the power to transport us to different worlds. Literature enriches our minds and broadens our perspectives. From classics to modern novels, there's something for everyone.",
        date: "2024-10-05",
        image: "https://vk.com/sticker/1-9137-512",
        comments: [],
    },
    {
        id: 6,
        title: "Understanding Climate Change",
        body: "Climate change is a pressing global issue. It affects ecosystems, weather patterns, and human health. Taking action to mitigate its effects is essential for a sustainable future.",
        date: "2024-10-06",
        image: "https://vk.com/sticker/1-9117-512",
        comments: [],
    },
    {
        id: 7,
        title: "The Beauty of Art",
        body: "Art is a form of expression that transcends language. It can evoke emotions, tell stories, and inspire change. From paintings to sculptures, art is a reflection of culture.",
        date: "2024-10-07",
        image: "https://vk.com/sticker/1-9167-512",
        comments: [],
    },
    {
        id: 8,
        title: "Exploring the Oceans",
        body: "Oceans cover more than 70% of the Earth's surface. They are home to diverse marine life and ecosystems. Exploring the oceans helps us understand the planet's health.",
        date: "2024-10-08",
        image: "https://vk.com/sticker/1-91117-512",
        comments: [],
    },
    {
        id: 9,
        title: "The Importance of Education",
        body: "Education is the foundation of a thriving society. It empowers individuals and drives economic growth. Access to quality education is a fundamental right for all.",
        date: "2024-10-09",
        image: "https://vk.com/sticker/1-9147-512",
        comments: [],
    },
    {
        id: 10,
        title: "The Wonders of Space",
        body: "Space exploration has always fascinated humanity. From landing on the moon to exploring Mars, space missions expand our knowledge. The universe holds endless possibilities.",
        date: "2024-10-10",
        image: "https://vk.com/sticker/1-5617-512",
        comments: [],
    }
];

export default postsData;